# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cd-ui-library

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Run Job'
        required: true
        default: 'build_storybook'
  push:
    paths: ["stories/**", "src/components/**"]
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
      - name: Run the tests and generate coverage report
        run:  npm test -- --coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build StoryBook
        run:  npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master 
          FOLDER: storybook-static
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
